export const articleMap: Record<string, string> = {
  憂鬱: 'https://www.leepsyclinic.com/search/label/憂鬱',
  焦慮: 'https://www.leepsyclinic.com/search/label/焦慮',
  恐慌: 'https://www.leepsyclinic.com/search/label/恐慌',
  憤怒: 'https://www.leepsyclinic.com/search/label/憤怒',
  悲傷: 'https://www.leepsyclinic.com/search/label/悲傷',
  快樂: 'https://www.leepsyclinic.com/search/label/快樂',
  壓力: 'https://www.leepsyclinic.com/search/label/壓力',
  感情: 'https://www.leepsyclinic.com/search/label/感情',
  家庭: 'https://www.leepsyclinic.com/search/label/家庭',
  職場: 'https://www.leepsyclinic.com/search/label/職場',
  人際: 'https://www.leepsyclinic.com/search/label/人際',
  婚姻: 'https://www.leepsyclinic.com/search/label/婚姻',
  親子: 'https://www.leepsyclinic.com/search/label/親子',
  自殺: 'https://www.leepsyclinic.com/search/label/自殺',
  自傷: 'https://www.leepsyclinic.com/search/label/自傷',
  危機: 'https://www.leepsyclinic.com/search/label/危機',
  創傷: 'https://www.leepsyclinic.com/search/label/創傷',
  失眠: 'https://www.leepsyclinic.com/search/label/失眠',
  睡眠: 'https://www.leepsyclinic.com/search/label/睡眠',
  工作: 'https://www.leepsyclinic.com/search/label/工作',
  學業: 'https://www.leepsyclinic.com/search/label/學業',
  生涯: 'https://www.leepsyclinic.com/search/label/生涯',
  諮商: 'https://www.leepsyclinic.com/search/label/諮商',
  心理治療: 'https://www.leepsyclinic.com/search/label/心理治療',
  心理師: 'https://www.leepsyclinic.com/search/label/心理師',
  精神科: 'https://www.leepsyclinic.com/search/label/精神科',
  自我探索: 'https://www.leepsyclinic.com/search/label/自我探索',
  情緒管理: 'https://www.leepsyclinic.com/search/label/情緒管理',
  自尊: 'https://www.leepsyclinic.com/search/label/自尊',
  孤獨: 'https://www.leepsyclinic.com/search/label/孤獨',
  完美主義: 'https://www.leepsyclinic.com/search/label/完美主義',
  霸凌: 'https://www.leepsyclinic.com/search/label/霸凌',
  分手: 'https://www.leepsyclinic.com/search/label/分手',
  失戀: 'https://www.leepsyclinic.com/search/label/失戀',
}

export const fallbackArticle: string = 'https://www.leepsyclinic.com/'
